
insert  into `t_biz_event`(`oid`,`name`,`store_name`,`description`,`start_time`,`end_time`,`enabled`,`opening_code`,`create_by`,`create_timestamp`,`update_by`,`update_timestamp`,`version`,`active`) values 
(1,'长宁店开业活动','长宁店','有抽奖','2017-07-18 00:00:01','2017-07-22 23:59:59',NULL,NULL,'admin','2017-07-22 08:08:15',NULL,NULL,0,1),
(2,'浦东店开业活动','浦东店','有路演','2017-08-01 00:00:01','2017-08-03 23:59:59',NULL,NULL,'admin','2017-07-22 08:08:23',NULL,NULL,0,1);
